----JOINING 
--THIS JOIN COMBINES TWO TABLES AND MAKES THEM INTO A THIRD. 
CREATE TABLE JOIN_1 AS
SELECT EMP_TITLE_ID,SEX, FIRST_NAME, LAST_NAME, SALARY
FROM SALARIES INNER JOIN Employees
                ON SALARIES.EMP_NO = EMPLOYEES.EMP_NO;
				

--JOINS MANAGER AND DEPT INFO

CREATE TABLE MANAGER_1 AS
SELECT DEPT_NO,EMPLOYEES.EMP_NO, FIRST_NAME, LAST_NAME 
FROM DEPT_MANAGER INNER JOIN Employees
                ON DEPT_MANAGER.EMP_NO = EMPLOYEES.EMP_NO;
---THIS MAKES A TABLE THAT COMBINES MANAGER INFO, DEPARTNMENT NO, AND DEPT NAME
CREATE TABLE MANAGER_2 AS
SELECT DEPT_NAME, MANAGER_1.DEPT_NO,EMP_NO, FIRST_NAME, LAST_NAME 
FROM DEPARTMENTS INNER JOIN MANAGER_1
                ON DEPARTMENTS.DEPT_NO = MANAGER_1.DEPT_NO;

---JOINS DEPT INFO AND EMPLOYEE INFO
CREATE TABLE EMPLOYEE_1 AS
SELECT DEPT_NO,EMPLOYEES.EMP_NO, FIRST_NAME, LAST_NAME 
FROM DEPT_EMP INNER JOIN Employees
                ON DEPT_EMP.EMP_NO = EMPLOYEES.EMP_NO;
---THIS MAKES A TABLE THAT COMBINES EMPLOYEE INFO, DEPARTNMENT NO, AND DEPT NAME
CREATE TABLE EMPLOYEE_2 AS
SELECT DEPT_NAME, EMPLOYEE_1.DEPT_NO,EMP_NO, FIRST_NAME, LAST_NAME 
FROM DEPARTMENTS INNER JOIN EMPLOYEE_1
                ON DEPARTMENTS.DEPT_NO = EMPLOYEE_1.DEPT_NO;
----------------SEARCHES-----------------------------------

--EMPLOYEES HIRED IN 1986

SELECT FIRST_NAME, LAST_NAME , HIRE_DATE
	FROM EMPLOYEES
	WHERE YEAR(HIRE_DATE)=86; 
	
---FIRST NAME HERCULES LAST NAME STARTS WITH "B"

SELECT FIRST_NAME, LAST_NAME, SEX
	FROM EMPLOYEES 
	WHERE FIRST_NAME = 'Hercules' AND LAST_NAME LIKE 'B%';
	
---ALL ASSOCIATES IN THE SALES DEPT

SELECT EMP_NO, FIRST_NAME, LAST_NAME, DEPT_NAME
	FROM EMPLOYEE_2 
	WHERE DEPT_NAME = 'Sales';

---ALL ASSOCIATES IN THE SALES AND DEVELOPMENT DEPARTMENTS

SELECT EMP_NO, FIRST_NAME, LAST_NAME, DEPT_NAME
	FROM EMPLOYEE_2 
	WHERE DEPT_NAME = 'Sales' OR DEPT_NAME = 'Development';
	
---FREQUENCY COUNTS OF LAST NAMES 
 SELECT LAST_NAME, COUNT(LAST_NAME)AS Frequency
	FROM EMPLOYEES
	GROUP BY LAST_NAME
	ORDER BY
	COUNT(LAST_NAME) DESC;